# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abf9d8798cd3fc357453671bf40c8d31a809825a8477ffaefa6dce09e1d0dc67617226ef8a05d9b802da7e1dcc7cafc2503a9bd76b9ac4a8e9648bbee2b24765

test:
  secret_key_base: 73469f4f8487d73ede655c277d4ba9aca5d1eda3d70e9d8b3c5381f5577f35bda66d69c93fa5ffaca2d63b89dc171c78aedc6ac4c3bf8ef92d865e66d2f6aeed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
